### ISSUE TITLE
Get sample ids for selected cases in trailblazer view

### ISSUE THREAD

**Issue by ChrOertlin** [Clinical-Genomics/trailblazer#504]
As a production user,
I want a feature to get all sample internal ids for the cases I have selected in the trailblazer analysis view,
So that my workflow of delivering samples in lims can be streamlined. Currently I need to open EACH case and MANUALLY copy the sample internal id to an external file to keep track of the sample I delivered. This is to ensure I can deliver the samples AGAIN in LIMS.

![image](https://github.com/user-attachments/assets/171be3d1-83ec-4eb0-b5d0-76a0c20b9bd3)

# Acceptance Criteria

Either
- [ ] A bulk action to get sample internal ids for selected cases
OR
- [ ] Automatic delivery of samples in LIMS that are set as DELIVERED in TRAILBLAZER 
...

# Notes

This is a wanted feature by production, signed off by @karlnyr and @Karl-Svard. 

Impact every production member
Saves n*10seconds PER SAMPLE in a case
Current workaround None.

# Implementation plan

- [ ] Work item 1
- [ ] Work item 2

**Comment by diitaz93** [comment]
Sent for refinement to @Clinical-Genomics/prodbioinfo

**Comment by karlnyr** [comment]
### Discussion

We find that some people may use this feature on a regular basis and that it would be nice to have integrated

### Acceptance criteria

- [ ] Have a button in the trailblazer analysis view that copies the unique samples of all cases selected

Note: It is planned to address the "Automatic delivery of samples in LIMS that are set as DELIVERED in TRAILBLAZER" in https://github.com/Clinical-Genomics/project-planning/issues/593
